name: Test
on: [ push ]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Prepare repo
        uses: actions/checkout@master
      - name: Test
        run: python3 -m unittest tests/__main__.py